# Site settings
title: Grigory Kruglov
email: grigory@kruglov.ca
description: "Grisha's blog"
baseurl: ""
url: "http://www.grigory.ca"

# Build settings
markdown: kramdown
permalink: :year/:month/:title/

collections:
    outdoors:
        title: Outdoors
        output: true
        permalink: /:year/:month/:title/
    programming:
        title: Programming
        output: true
        permalink: /:year/:month/:title/
    thoughts:
        title: General Writing
        output: true
        permalink: /:year/:month/:title/
    videos:
        title: Videos
        output: true
        permalink: /:year/:month/:title/
