# Site settings
title: Grigory Kruglov
email: grigory.kruglov@gmail.com
description: "Grigory's personal blog on tech, web development, startups, and various musings"
baseurl: ""
url: "http://www.grigory.ca"

# Build settings
markdown: kramdown
permalink: :year/:month/:title/
