# Site settings
title: Grigory Kruglov
email: grigory@kruglov.ca
description: "← say hi, and hopefully enjoy the ↑"
baseurl: ""
url: "http://www.grigory.ca"

# Build settings
markdown: kramdown
permalink: :year/:month/:title/
